---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: smbdxfortunes
  namespace: default
  labels:
    app: smbdxfortunes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smbdxfortunes
  template:
    metadata:
      labels:
        app: smbdxfortunes
    spec:
      containers:
      - name: smbdxfortunes
        image: nullset2/smbdxfortunes:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: smbdxfortunes

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: smbdxfortunes
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nullset2-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    traefik.frontend.rule.type: PathPrefix
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: smbdxfortunes
          servicePort: 80
      - path: /smbdxfortunes
        backend:
          serviceName: smbdxfortunes
          servicePort: 80
      - path: /pixy
        backend:
          serviceName: pixy
          servicePort: 80
  tls:
    - secretName: nullset2-tls
      hosts:
        - ${DOMAIN}

