---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: smbdxfortunes
  namespace: default
  labels:
    app: smbdxfortunes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smbdxfortunes
  template:
    metadata:
      labels:
        app: smbdxfortunes
    spec:
      containers:
      - name: smbdxfortunes
        image: nullset2/smbdxfortunes:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: web
          containerPort: 4567
---
apiVersion: v1
kind: Service
metadata:
  name: smbdxfortunes

spec:
  ports:
    - name: web
      port: 80
      targetPort: web

  selector:
    app: smbdxfortunes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smbdxfortunes-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
    traefik.frontend.rule.type: PathPrefix
spec:
  ingressClassName: traefik
  rules:
  - host: ${DOMAIN}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: smbdxfortunes
            port:
              number: 80
      - path: /smbdxfortunes
        pathType: Prefix
        backend:
          service:
            name: smbdxfortunes
            port:
              number: 80
  tls:
    - secretName: nullset2-tls
      hosts:
        - ${DOMAIN}
