development:
  adapter: postgresql
  encoding: unicode
  database: smbdxfortunes_development
  pool: 2
  username: alfredo
  password:
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>