CREATE TABLE Fortunes(type_id integer NOT NULL, content varchar(40), created_at timestamp DEFAULT current_timestamp, updated_at timestamp DEFAULT current_timestamp);

INSERT INTO Fortunes 
VALUES (1, 'With a Fire Flower you''ll beat Bowser.'),
    (1, 'Fortune awaits you in the clouds.'),
    (1, 'Fortune will lead you to Yoshi.'),
    (1, 'Look below to find what you seek.'),
    (1, 'Seek out the one who thinks of you.'),
    (1, 'Good friends bear good news.'),
    (1, 'Southerly winds bring sunny skies.'),
    (1, 'Kindness given is returned tenfold.'),
    (1, 'Good news is due from a loved one.'),
    (1, 'Good things come from hard work.'),
    (1, 'Soothing music soothes the soul.'),
    (1, 'Keep a good grasp Fortune will last.'),
    (1, 'Worries naturally melt away.'),

    (2, 'Stomp a shell and scores will swell.'),
    (2, 'Pipe cleaning reaps rewards.'),
    (2, 'Words of the wise cast fears aside.'),
    (2, 'An eye to the sky reveals Red Coins.'),
    (2, 'Keep your head up Find what you seek.'),
    (2, 'A party of three brings good luck.'),
    (2, 'Luck arrives with the easterly wind.'),
    (2, 'Express yourself with written word.'),
    (2, 'Active bodies breed active minds.'),
    (2, 'To create music is to create joy.'),
    (2, 'You shall achieve great victories.'),

    (3, 'Enemies lurk in watery depths.'),
    (3, 'Fortune is hidden in bricks unbroken.'),
    (3, 'Today is your day to win the race.'),
    (3, 'Boxes may contain clues to the quest.'),
    (3, 'Victory is yours in the coming race.'),
    (3, 'Beware of winds from the west.'),
    (3, 'Solutions are within your grasp.'),
    (3, 'Feelings shared will be understood.'),
    (3, 'He who thinks of you is beside you.'),
    (3, 'Imagination is a wonderful toy.'),
    (3, 'Old tunes bring new fortune.'),
    (3, 'Trade high scores to set new goals.'),

    (4, 'Stomping on spikes leads to sore feet.'),
    (4, 'Careless footing causes one to fall.'),
    (4, 'Kicked shells may bounce back.'),
    (4, 'What you seek is right beside you.'),
    (4, 'Sincere apologies renew friendships.'),
    (4, 'Storms ride in on northerly winds.'),
    (4, 'You will not find true love this day.'),
    (4, 'A VS Mode victory is not your fate.'),
    (4, 'Not all pain leads to gain.'),
    (4, 'Happy songs lift sad moods.'),
    (4, 'The Warp Zone speeds success.'),
    (4, 'Only a Challenge clears the mind.'),

    (5, 'Bowser''s breath engulfs the future.'),
    (5, 'Flying Koopas cut short success.'),
    (5, 'Dont count Yoshis before they hatch.'),
    (5, 'Leave impossible dreams to dreamers.'),
    (5, 'Seek answers in a friends advice.'),
    (5, 'Beware of pointed enemies.'),
    (5, 'Change old habits Yield new success.'),
    (5, 'Victory in a race may wash pain away.'),
    (5, 'Excess is a powerful enemy.'),
    (5, 'Favorite tunes never fade.'),
    (5, 'Now is the time for patience.'),
    (5, 'Help all in need, not just a friend.');
